language: node_js
node_js:
  - "12"
cache: npm

before_script:
- yarn build
- yarn eslint

deploy:
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    on:
      repo: ealush/n4s
      branch: master
